### ISSUE TITLE
Missing init tables patient, record, data_ingested

### ISSUE THREAD

**Issue by nekozzz94** [ibrahim-Sobh/heart_stroke_prediction#3]
I face issue when running local (already run createdb.py)
`sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "record" does not exist
LINE 1: INSERT INTO record (file_name, doctor_first_name, doctor_las...
                    ^

[SQL: INSERT INTO record (file_name, doctor_first_name, doctor_last_name, createdon) VALUES (%(file_name)s, %(doctor_first_name)s, %(doctor_last_name)s, %(createdon)s) RETURNING record.id]
[parameters: {'file_name': '-', 'doctor_first_name': 'inu', 'doctor_last_name': 'chan', 'createdon': datetime.datetime(2023, 2, 6, 16, 45, 37, 703804)}]
(Background on this error at: https://sqlalche.me/e/14/f405)`

It's ok if I add this line into createdb.py before running
`import models`

**Comment by ibrahim-Sobh** [comment]
yes
